name: "Composite Hello World"
description: "A composite action that prints a Hello World message using two inputs."
inputs:
  first_name:
    description: "First name to greet"
    required: true
    default: "Hello"
  last_name:
    description: "Last name to greet"
    required: false
    default: "World"
runs:
    using: "composite"
    steps:
      - run: echo "${{ inputs.first_name }} ${{ inputs.last_name }} from GitHub Actions!"
        shell: bash