name: PowerShell でトレーシングオプションを試す

on: [push]

jobs:
  run-cmd-tracing-option:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run PowerShell script with tracing
        run: |
          # https://learn.microsoft.com/ja-jp/powershell/module/microsoft.powershell.core/set-psdebug?view=powershell-7.4
          Set-PSDebug -Trace 1
          git --version
          git branch
          dir
          az --version
          Write-Host "Hello, world."
          Set-PSDebug -Trace 0
          
      - name: Run PowerShell script file with tracing
        run: |
          Set-PSDebug -Trace 1
          ./scripts/pws-action.ps1
          Set-PSDebug -Trace 0
  
