name: PowerShell でトレーシングオプションを試す

on: [push]

jobs:
  run-cmd-tracing-option:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run PowerShell script with tracing
        run: |
          $PSDebugPreference = "Continue"
          git --version
          git branch
          dir
          az --version
          Write-Host "Hello, world."
  
